### PR TITLE
Add a CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by rafaelgonzalez**
@neilang @waitingallday thoughts?

[Preview here](https://github.com/marcom-unimelb/nexus-gem/blob/contributing-guide/CONTRIBUTING.md)

### CODE REVIEW

**Comment by waitingallday** [comment]
Looks good to me 👍

**Comment by rafaelgonzalez** [comment]
Now that 100% coverage actually is in (#7), we can merge this.

Nothing to add @neilang ?

**Comment by neilang** [comment]
Sorry I didn't see this earlier. Looks good to me. My only feedback: `^betterspec.org^betterspecs.org^`

**Comment by rafaelgonzalez** [comment]
Nice catch @neilang, I'll update it.

**Pull request merged**
